// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	ApiGateway "github.com/SIN5t/tiktok_v2/cmd/api/biz/router/ApiGateway"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	ApiGateway.Register(r)
}
