// Code generated by hertz generator.

package ApiGateway

import (
	"context"

	ApiGateway "github.com/SIN5t/tiktok_v2/cmd/api/biz/model/ApiGateway"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UserRegister .
// @router /douyin/user/register/ [POST]
func UserRegister(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ApiGateway.DouyinUserRegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ApiGateway.DouyinUserRegisterResponse)

	c.JSON(consts.StatusOK, resp)
}
