server:
  name: "TiktokApiGateway"
  host: 0.0.0.0  # 试试和127.0.0.1的区别
  port: 8888
  limit:
    capacity: 200
    rate: 20
    tokenInit: 128  # 初始令牌个数

JWT:
  signingKey: "myKey"




Etcd:
  enable: true
  host: 0.0.0.0 //这是监听的host，表示监听来自任何 IP 地址的连接请求
  port: 2379

otel:
  host: 0.0.0.0
  port: 4317
Hertz:
  useNetPoll: false
  tls:
    enable: false
    keyFile: ""
    certFile: ""
    ALPN: true
  http2:
    enable: false
    keyFile: ""
    certFile: ""
    ALPN: true
