MysqlUser = "root"
MysqlPswd = "123456"
MysqlAddr = "localhost:3306"
MysqlName = "tiktok"
RedisAddr = "localhost:6379"
RedisPswd = "123456"

MinioEndpoint = "h2eonr2x.shenzhuo.vip:38854"
MinioAccessKeyID = "minioadmin"
MinioSecretAccessKey = "minioadmin"
JWTSecret = "f05ad7412aa192ddc121ba50a64e585943b3e6d8fca4a3a19a8eea26e76496a7"