mysql:
  source:
    driverName: mysql
    host: 0.0.0.0
    port: 3307
    database: tiktok
    username: root
    password: 123456
    charSet: utf8mb4

  replica1:
    driverName: mysql
    host: 127.0.0.1
    port: 3307
    database: tiktok
    username: root
    password: 123456
    charSet: utf8mb4

  replica2:
    driverName: mysql
    host: 127.0.0.1
    port: 3309
    database: tiktok
    username: root
    password: 123456
    charSet: utf8mb4

redis:
  addr: 0.0.0.0
  port: 6379
  password: 123456
  video_db: 0
  user_db: 1
  pool_size: 30
  min_idle_conns: 30