server:
  host: localhost
  port: 9000

MINIO_ROOT_USER: minioadmin
MINIO_ROOT_PASSWORD: minioadmin

video_bucket: video
pic_bucket: picture
contentType:
  video: video/mp4
  pic: image/jpeg

location: us-east-1